services:
  - type: web
    name: factoryline-broadcast-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DB_USER
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_PORT
        sync: false
      - key: PORT
        value: 10000
      - key: URL
        sync: false
